### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by nettsite** [shuvroroy/filament-spatie-laravel-backup#17]
Hi,

I don't know if this is a bug or me doing something wrong: after installing the package, I see the Backup item on the menu and when I try it, I get the following error:

`Illuminate  Database QueryException`
`could not find driver`
`create table "backup_destination_statuses" ("id" integer not null primary key autoincrement, "name" varchar, "disk" varchar, "reachable" varchar, "healthy" varchar, "amount" integer, "newest" varchar, "usedStorage" varchar)`

The Spatie package was installed and running before I installed filament-spatie-laravel-backup, and is still working fine from the command line.

All configs are default.

**Comment by NettSite** [comment]
Fixed - found the solution on Discord: https://discord.com/channels/883083792112300104/927269672133492816/968842506127179796

**Comment by nikitabuida** [comment]
So to fix this issue you need to enable sqlite3 php extension.

Windows/Laragon: enable sqlite3 and pdo_sqlite extensions and restart Apache.
Linux/Ubuntu: sudo apt install php8.1-sqlite3 and restart Apache

**Comment by rgasch** [comment]
Can someone please explain why this package needs the sqlite driver, I want to backup Mysql, why do I need Sqlite for this?

**Comment by rgasch** [comment]
I've dug into the code for this ... the reason for this behavior is that the spatie backup package is designed this way (it uses a package called Sushi which implements saving model data to a sqltite database) ... so this is part of the underlying package's functionality.

**Comment by Saifallak** [comment]
this should be mentioned in docs ? i had troubles making it work til i found this issue
