### ISSUE TITLE
Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT"

### ISSUE THREAD

**Issue by bernhardh** [shuvroroy/filament-spatie-laravel-backup#20]
When clicking on "Create Backup" and then on "only DB" (or any other option) it runs endless. In laravel.log I get `Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT"`? 

Running spatie backup from commandline `php artisan backup:run` works without any problems.

**Comment by drakedraco** [comment]
I modified the code in CreateBackUpJob

Artisan::call('backup:run' . $this->option);

And removed everything else 

And modified the backups.blade.php  button actions

     <x-filament::button wire:click="create(' --only-db')" color="primary">

     <x-filament::button wire:click="create(' --only-files')" color="warning">

     <x-filament::button wire:click="create()" color="success">

    It now works as expected for me at least

**Comment by shuvroroy** [comment]
This might help you guys.
https://github.com/spatie/laravel-backup/issues/1445

**Comment by MarJose123** [comment]
Hi Guys, I found a temporarily solution, I extended the Backups page class and modify to this

```php
namespace App\Filament\Pages;

use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups as BaseBackups;
use Spatie\Backup\Tasks\Backup\BackupJobFactory;

class Backups extends BaseBackups
{
    use HasPageShield;


    public function create(string $option = ''): void
    {
        $backupJob = BackupJobFactory::createFromArray(config('backup'))->disableSignals();

        if ($option === 'only-db') {
            $backupJob->dontBackupFilesystem();
        }

        if ($option === 'only-files') {
            $backupJob->dontBackupDatabases();
        }

        if (! empty($option)) {
            $prefix = str_replace('_', '-', $option).'-';

            $backupJob->setFilename($prefix.date('Y-m-d-H-i-s').'.zip');
        }

        $backupJob->run();

        $this->dispatchBrowserEvent('close-modal', ['id' => 'backup-option']);

        $this->notify('success', __('filament-spatie-backup::backup.pages.backups.messages.backup_success'));
    }
}
```

**Comment by jastranlove2020** [comment]
Thank you for your solution. Spatie should fix this because it is as a bug on Windows OS without supporting SIGNAL.

Above MarJose123 should be fine as hot fix because Backup runs fine with command line mode on the Windows OS.

You can disable SIGNAL option at file vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php after run func by adding $this->disableSignals();, but you will need to override again after new update from this backup package if it is not fixed yet.

**Comment by fetova** [comment]
I've added this on post-autoload-dump section of composer.json:

"sed -i 's/\\$signals = true;/\\$signals = false;/g' vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php"

I don't get why but it seems that the library should call php-cli and is not doing it

**Comment by kayvanaarssen** [comment]
This is also not working on a Linux Machine. Tried this on a server hosed on Ploi and RunCloud same issue.
`php artisan backup:run` on CLI will work without an issue. Only via the GUI the job will be pushed to the queue as Sync. And will never run.

**Comment by faizananwerali** [comment]
https://github.com/shuvroroy/filament-spatie-laravel-backup/pull/55 This solution looks good to me.
