### ISSUE TITLE
JS error when creating a backup

### ISSUE THREAD

**Issue by realslimsutton** [shuvroroy/filament-spatie-laravel-backup#21]
After clicking a button to generate a backup, I would expect the modal to close and the job to be queued.

However, what's happening is the modal stays open and nothing happens. Job doesn't get queued and the modal does not close.

Fresh install of spatie-backup and filament-spatie-backup, with default configs. Running the spatie backup command manually in the console works correctly.
![Screenshot 2022-07-04 053949](https://user-images.githubusercontent.com/87341175/177082623-5da11a00-7c4c-40bf-b6b0-8c623b5798c5.png)

**Comment by shuvroroy** [comment]
@realslimsutton It will better if you post the response.

**Comment by realslimsutton** [comment]
> @realslimsutton It will better if you post the response.

I'm not quite sure what you mean. How would I find the response?

**Comment by realslimsutton** [comment]
> @realslimsutton It will better if you post the response.

Nevermind, I'm stupid haha.

I've attached the response below. I see there's another issue that's currently open that mentions this exception so I'll have a look there.
[response.txt](https://github.com/shuvroroy/filament-spatie-laravel-backup/files/9036419/response.txt)

Thanks!

**Comment by shuvroroy** [comment]
For now you can check this issue.
https://github.com/shuvroroy/filament-spatie-laravel-backup/issues/20
