### ISSUE TITLE
Allow to integrate/use Filament shield for roles and Permission

### ISSUE THREAD

**Issue by MarJose123** [shuvroroy/filament-spatie-laravel-backup#29]
Allow to add ` use HasPageShield;` traits based on this documentation.

https://github.com/bezhanSalleh/filament-shield#pages

**Comment by shuvroroy** [comment]
Create a custom page class and that class will be extend `Backups` class. After that register in config file.

```php

<?php

namespace App\Filament\Pages;

use ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups::class as BaseBackups;

class Backups extends BaseBackups
{
      use HasPageShield;
}
```

**filament-spatie-laravel-backup.php**
```php
'pages' => [
        'backups' => \ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups::class
],
```
