### ISSUE TITLE
Package doesn't seem to work

### ISSUE THREAD

**Issue by rgasch** [shuvroroy/filament-spatie-laravel-backup#30]
I've installed this package and it doesn't seem to work. 

Clicking "Create Backup" gives me the popup/modal to pick the type of backup I want to make, but when selecting a backup, even though it tells me that a backup is being done in the background, nothing seems to happen. 

Using the default spatie backup artisan commands, I can take a backup and then doing a "php artisan backup:list" shows me the new backup but the filament plugin does not show this backup. 

As such, it would seem that something fundamental is wrong here. Please advise.

**Comment by frizcool** [comment]
mee too, only show pop up "run in background" but still not work

**Comment by aeq-dev** [comment]
same here !

**Comment by aeq-dev** [comment]
I fixed it by installing php8.1.sqlit3 and enable pdo_sqlit, sqlit3 then restart the server :)

**Comment by martinschenk** [comment]
i have the same issue. In my logfile:

```txt
local.ERROR: Connection could not be established with host "localhost:1025": stream_socket_client(): Unable to connect to localhost:1025 (Connection refused) {"userId":1,"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"localhost:1025\": stream_socket_client(): Unable to connect to localhost:1025 (Connection refused) at .../vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)
[stacktrace]
```
and

```txt
local.ERROR: The dump process failed with a none successful exitcode.
Exitcode
========
127: Command not found

Output
======
<no output>

Error Output
============
sh: mysqldump: command not found
 {"userId":1,"exception":"[object] (Spatie\\DbDumper\\Exceptions\\DumpFailed(code: 0): The dump process failed with a none successful exitcode.
Exitcode
========
127: Command not found

Output
======
<no output>

Error Output
============
sh: mysqldump: command not found
 at ..../vendor/spatie/db-dumper/src/Exceptions/DumpFailed.php:14)
[stacktrace]
```

**Comment by stephen-morlex** [comment]
> I fixed it by installing php8.1.sqlit3 and enable pdo_sqlit, sqlit3 then restart the server :)

I have the same issue, I did enable pdo_sqlit and sqlit3 restarted my server but still not working.

**Comment by KaanTanis** [comment]
@shuvroroy

**Comment by zoidboi** [comment]
> i have the same issue. Backups with spatie backup are working with: php artisan:backup But backups with Filamente backup give me this error message in in my logfile:
> 
> ```
> local.ERROR: Connection could not be established with host "localhost:1025": stream_socket_client(): Unable to connect to localhost:1025 (Connection refused) {"userId":1,"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Connection could not be established with host \"localhost:1025\": stream_socket_client(): Unable to connect to localhost:1025 (Connection refused) at .../vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)
> [stacktrace]
> ```
> 
> and
> 
> ```
> local.ERROR: The dump process failed with a none successful exitcode.
> Exitcode
> ========
> 127: Command not found
> 
> Output
> ======
> <no output>
> 
> Error Output
> ============
> sh: mysqldump: command not found
>  {"userId":1,"exception":"[object] (Spatie\\DbDumper\\Exceptions\\DumpFailed(code: 0): The dump process failed with a none successful exitcode.
> Exitcode
> ========
> 127: Command not found
> 
> Output
> ======
> <no output>
> 
> Error Output
> ============
> sh: mysqldump: command not found
>  at ..../vendor/spatie/db-dumper/src/Exceptions/DumpFailed.php:14)
> [stacktrace]
> ```

The first issue is not having the mail configured correctly. A dev fix would be for example to set: MAIL_MAILER in your .env to "log"

The second issue about not finding mysqldump is an oversight of the installation guide of this package:
If you use mysql you should open the file: config/database.php and adding to the "connections" -> "mysql" array:
`'dump' => [
                'dump_binary_path' => '/your/path/to/mysqldump/bin', // DO NOT include mysqldump, only the path to bin.
            ],`

This information was available here: https://spatie.be/docs/laravel-backup/v8/installation-and-setup#:~:text=Here%27s%20an%20example%20for%20MySQL%3A

**Comment by Mohammad-Yasin-Noori** [comment]
my installation does not contain CREATE BACKUP button

**Comment by shuvroroy** [comment]
Please follow this
https://spatie.be/docs/laravel-backup/v8/installation-and-setup#content-dumping-the-database

**Comment by abbasmashaddy72** [comment]
I tried to use Queue and setup the config file but still same no change still not wrking

**Comment by norouzimohammadreza** [comment]
> I tried to use Queue and set up the config file but still same no change, still not working
> 
> `php artisan backup:run` Works this added up the file in Table

Have you solved it?
