### ISSUE TITLE
How to set 'backup.pages.backups.navigation.group'

### ISSUE THREAD

**Issue by eugenevdm** [shuvroroy/filament-spatie-laravel-backup#33]
Hi apologies for raising a total noob question, but how do I set the:

> backup.pages.backups.navigation.group

I see the class make provision for it. I have publish the config but the config is sparse and I only see this:

```php
return [
...
    'pages' => [
        'backups' => \ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups::class
    ],
...
    'polling' => [
        'interval' => '4s'
    ],
...
    'queue' => null,

];
```

I presume it's something fundamental about Filamentphp that I don't understand but I don't know where to start. 

I tried raising this problem in GitHub Q&A for this repo but the hyperlink says 404.

**Comment by eugenevdm** [comment]
I've made some progress. I see it's in the vendor's resources/lang/en folder. Not entirely sure if it's actually configurable without code changes as then one would have to accommodate all the languages files. Perhaps something like this?

English

```php

'navigation' => [
				'group' =>  config('filament-spatie-laravel-backup.navigationGroup', 'Settings'),
				'label' => config('filament-spatie-laravel-backup.navigationLabel', 'Backups'),
			],
...

Spanish

```php
'navigation' => [
				'group' =>  config('filament-spatie-laravel-backup.navigationGroup', 'Configuraciones'),
				'label' => config('filament-spatie-laravel-backup.navigationLabel', 'Respaldos'),
			],
...


Comments? Happy to do a pull request.

**Comment by shuvroroy** [comment]
@eugenevdm need to do similar like other lang
https://github.com/shuvroroy/filament-spatie-laravel-backup/tree/main/resources/lang

**Comment by eugenevdm** [comment]
@shuvroroy I don't understand. Is there a way to configure the group in the file `config/filament-spatie-laravel-backup` ?

If not, do I first copy the language files across and then make then changes? If I copy them across, to where do I copy them?

**Comment by shuvroroy** [comment]
@eugenevdm using config no options. We already have translation for Spanish. I don't have any clear idea what you want to achieve. 
https://github.com/shuvroroy/filament-spatie-laravel-backup/pull/13/files

**Comment by eugenevdm** [comment]
Hi @shuvroroy . 

I want to change the name of the navigation group. At present the navigation group in English is "Settings". I want to change it to "System".

**Comment by shuvroroy** [comment]
Hi @eugenevdm 

Just publish the package lang folder change it for en.
```php
'navigation' => [
    'group' => 'Settings', // Your one System
    'label' => 'Backups',
],

**Comment by eugenevdm** [comment]
I just don't get it.

```bash
✗ php artisan vendor:publish --tag="filament-spatie-laravel-backup" 


   INFO  No publishable resources for tag [filament-spatie-laravel-backup].  
```

**Comment by shuvroroy** [comment]
@eugenevdm You are using wrong command. Use this one

```php
php artisan vendor:publish --tag="filament-spatie-backup-translations"
```
