### ISSUE TITLE
Change the destination disk

### ISSUE THREAD

**Issue by SergioGMR** [shuvroroy/filament-spatie-laravel-backup#37]
I don't know exactly how to change the destination disk of the backup.
I tried to follow the **Spatie** instructions but in the **filament-*.php** file and I just only success to change the _"name"_.

Thanks in advance.

**Comment by cgiupponi** [comment]
same question

**Comment by shuvroroy** [comment]
@cgiupponi Read this https://spatie.be/docs/laravel-backup/v7/taking-backups/overview#content-determining-the-content-of-the-backup

**Comment by shuvroroy** [comment]
I already mentioned please check.
<img width="885" alt="Screenshot 2024-01-19 at 7 16 11 PM" src="https://github.com/shuvroroy/filament-spatie-laravel-backup/assets/21066418/2bf48727-180e-41d3-bdf8-af8c393348a6">

Anyhow 
`php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"
`
