### ISSUE TITLE
No Create Backup button

### ISSUE THREAD

**Issue by Larry-Home** [shuvroroy/filament-spatie-laravel-backup#45]
Installed this and spatie packages and backups are working from the php artisan commands.  They are listed in the Filament UI but there is no Create Backup botton shown, nor can backups be downloaded / deleted.

**Comment by schroeder-hesel** [comment]
Hi, i experienced the same issue. After some searching i found out that the actions are only visible when the user has the permissions (create-backup, download-backup, delete-backup) for it. This should be mentioned in the readme.

https://github.com/shuvroroy/filament-spatie-laravel-backup/blob/4d817a2c74131cda243753acd06dc642a656f0d7/src/Pages/Backups.php#L32-L41

https://github.com/shuvroroy/filament-spatie-laravel-backup/blob/4d817a2c74131cda243753acd06dc642a656f0d7/src/Components/BackupDestinationListRecords.php#L57-L73

**Comment by MarJose123** [comment]
I have the same issue.

**Comment by Larry-Home** [comment]
@schroeder-hesel Thanks for pointing out those items in the code.  This definitely seems to be something that needs to be documented.

I, like @MarJose123 am looking to do exactly the same thing - integrate this with Filament Shield.  Any chance somebody has went through this process and can share the steps?  If not, I will dig into this further when time allows.  

Again, appreciate the information!

**Comment by schroeder-hesel** [comment]
@Larry-Home  Since Filament Shield is using spatie/laravel-permission, can't you just add the mentioned permissions to the role of your user? I am using spatie/laravel-permission without Shield and it is working fine.

**Comment by MarJose123** [comment]
> @schroeder-hesel Thanks for pointing out those items in the code. This definitely seems to be something that needs to be documented.
> 
> I, like @MarJose123 am looking to do exactly the same thing - integrate this with Filament Shield. Any chance somebody has went through this process and can share the steps? If not, I will dig into this further when time allows.
> 
> Again, appreciate the information!

I've downgraded to v1.2.6, as this release it don't have yet permission setup.

**Comment by Larry-Home** [comment]
Yes, manually adding the permissions to a role worked.  I did create a unique role just for this otherwise if you used the Shield UI to manage a role with these they would be lost.  Appreciate the help!
