### ISSUE TITLE
Limit users with other roles from accessing this part

### ISSUE THREAD

**Issue by ehs4nm** [shuvroroy/filament-spatie-laravel-backup#5]
Hi.

How could someone limit access to the backup part based on permission or roles?

**Comment by shuvroroy** [comment]
@ehs4nm Yes you can. By extending the `\ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups::class` class. And then register your class in filament-spatie-backup-config file

`
'pages' => [
       'backups' => YourCustomClass::class
 ],
`

**Comment by ehs4nm** [comment]
I create a page class  and extend it from '\ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups::class'. Registered it as you said. In the class i defined "'protected static string $view = 'filament-spatie-backup::pages.backups';"
Now i have the page in my navigation.
I followed the instruction in docs (https://filamentphp.com/docs/2.x/admin/pages#conditionally-hiding-pages-in-navigation) but now i get; "Call to undefined method App\Models\User::canManageSettings() ".
my user implemented "FilamentUser". but still i get this!

**Comment by shuvroroy** [comment]
@ehs4nm I think there is no method name `canManageSettings` in User Model. You need to implement it first

**Comment by nikitabuida** [comment]
> @ehs4nm Yes you can. By extending the `\ShuvroRoy\FilamentSpatieLaravelBackup\Pages\Backups::class` class. And then register your class in filament-spatie-backup-config file
> 
> `'pages' => [ 'backups' => YourCustomClass::class ],`

Works great. Thank you!

Guess you can close this issue.
