### ISSUE TITLE
back up on bg no working event i start queue:work

### ISSUE THREAD

**Issue by DeviJv** [shuvroroy/filament-spatie-laravel-backup#83]
sh: mysqldump: command not found on my logs

**Comment by kingmaker-agm** [comment]
I am also getting the same Error. I can confirm `mysqldump` accessible in my terminal and also `php artisan backup:run` running successfully.

@DeviJv did you find the solution to this?

**Comment by DeviJv** [comment]
ya change the path where is mysqldump stay

**Comment by kingmaker-agm** [comment]
@DeviJv I have done that as well and it didn't work out.

BTW, I was on a windows environment.

If you could able to get your working, Would you mind sharing the **config file**?
